# Generated by Django 4.2.4 on 2023-08-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teamname', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('creationtime', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='User.user')),
                ('members', models.ManyToManyField(help_text='Select members for this team', max_length=50, to='User.user')),
            ],
        ),
    ]
